### ISSUE TITLE
Linux Debian module pixel init error

### ISSUE THREAD

**Issue by Panciz** [kitao/pyxel#125]
Error import main pyxel module.

```
>> from pyxel.examples import install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/panci/.local/lib/python3.5/site-packages/pyxel/__init__.py", line 12
    DEFAULT_BORDER_COLOR:int = constants.DEFAULT_BORDER_COLOR
```

Python version

```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
```

I installed the package using pip3

`pip3  install --user  pyxel`

Debian Stretch
Python 3.5.3

**Comment by GitRenhl** [comment]
Python 3.6 have new feature https://www.python.org/dev/peps/pep-0526/ so Pyxel doesn't support older python version

**Comment by skamieniarz** [comment]
As @GitRenhl already mentioned, you would need a Python 3.6 version or newer to make it running. You won't install it out of the box on Debian since it's not yet in the stable repository but you can build it on your own (for instance, using instructions from [https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-debian-9/](https://www.rosehosting.com/blog/how-to-install-python-3-6-4-on-debian-9/)).
