### ISSUE TITLE
pyxel error: invalid screen size in 'System'

### ISSUE THREAD

**Issue by timbledum** [kitao/pyxel#151]
**Describe the bug**
Getting this error:

    pyxel error: invalid screen size in 'System'

On snake.py. https://github.com/timbledum/snake

Not a very descriptive error unfortunately, and no stack trace.

This game worked under pyxel 1.0.x Some adjustments required to get this to otherwise work under 1.1.x (see below).

**To Reproduce**
Steps to reproduce the behaviour:
Run snake.py under MacOS

I had to hardcode the constants for font width and height as the constants module had moved.

**Desktop (please complete the following information):**
 - MacOS

Cheers! :) Marcus

**Comment by timbledum** [comment]
Just thinking – is there a secret minimum for width and height in the `pyxel.init()` call?

**Comment by kitao** [comment]
I removed the min size limit of the screen in 1.1.6. It it unnecessary on the SDL version of the engine.

**Comment by kitao** [comment]
Hi @timbledum. Actually I like your Snake game very much!

So if possible I would like to use your Snake game as Pyxel's official example. 
(I originally intended to use only 100 lines of sample code only, but I think some sample can be long now)

Is is OK import your code for sample?
And is it also OK to reformat it with black formatter and use ``playm`` command instead of set of ``play`` commands for playing BGM?

**Comment by timbledum** [comment]
That would be awesome! Absolutely happy for you to do that, and happy for you to make any changes/modifications required - go nuts. I'm not precious.

**Comment by kitao** [comment]
Thank you!
