### ISSUE TITLE
blt(x, y, img, u, v, w, h, [colkey]) manipulation

### ISSUE THREAD

**Issue by uturuncuayaku** [kitao/pyxel#207]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

I'm always frustrated when trying to rotate pyxel.blt()..I may be very new to Python but not coding and I cant figure out how to rotate this image Ive created and loaded properly into the engine because of a lack of documentation. Can I wrap a pyxel object, specificially the BLT function to rotate and manipulate at will without using the pyxeleditor because there is insufficient documentation on how to make it work as well. In two days Ive waded through a lot of code and nothing is written well enough at the moment. I just want to make a spaceship with a vector and that can spin on at the center of its location. Retro asteroids or a retro version of Geometry Wars is my end goal.

**Describe the solution you'd like**
I would like to rotate or find all the coordinates of pyxel.blt() objects. Should I use numpy or another engine?

**Describe alternatives you've considered**
To rotate(pyxel.blt()) and within my rotate class calculating all the new coordinates like a picture or 2D object is my dream but at least find all points of my pyxel.blt object or image and manipulate how I wish within my window.
Ive managed to rotate my spaceship around a point or any given points I want but it always faces up and I could potentially use blt(x, y, img, u, v, w, h, [colkey]) and then negate W and negate H to create the illusion of graphic spinning upside down and mirroring vertically. But I would like to avoid this as it would potentially make my code unusable in the future.

**Additional context**
Please more documentation on how to use Tilemap and Pyxel Editor and thank you so much .. so far everything looks so good but I cant manipulate it well enough for my specific liking. I believe updating documentation maybe to say this works as a linear game instead of a 2D game would be an important thing to note. I'm sorry if I sound mean but I'm very new to Python and almost done with my game.

**Comment by orlnub123** [comment]
I'm not sure if you've figured out a solution so sorry if this is extraneous.

You can't rotate images drawn with `blt`, it only does a 1:1 copy (possibly in reverse) of a portion of your choosing from the image bank. Here's stuff you could do instead:
* Only rotate in 4 directions (up, down, left, right) by using two images, one horizontal and the other vertical, and drawing either one based on the direction, and in reverse when going backwards.
If the rotation directions are diagonal you could get away with only using a single image.
* Fill the image bank with manually rotated versions of the same image, from 0° to 45°, with the amount of images based on how granular you want the rotation to be.
* Draw your spaceship with shapes instead of images.

I do think it would be a nice feature to add an angle argument to `blt` but someone would have to implement it.

**Comment by kitao** [comment]
If add some `angle` option to the `blt`, It also needs the center of the rotation. And it can't keep simplicity Pyxel want to be. So please try the way @orlnub123 proposed.
