### ISSUE TITLE
Not enough examples/documentation about some methods

### ISSUE THREAD

**Issue by nejdetckenobi** [kitao/pyxel#229]
I am trying to understand the logic behind 

- `tilemap().set()` 
- `tilemap().bltm()`

but I couldn't! 
Looking to the third example in order to understand it, still no luck! 
Some clarifications for the methods would be appreciated.

Because of that, I can not load a tilemap and draw a tile properly.

**Comment by nejdetckenobi** [comment]
I noticed that it only creates new image or modifies current data.

**Comment by timbledum** [comment]
I feel like we need a whole separate navigable docs page for this project... but I'm not about to put in the effort to help putting it in place! :p

**Comment by ddekany** [comment]
Instead of writing a separate documentation for the methods and classes, there should be Docstring in the source code. Then the IDE/editor can show it, and the documentation can be generated.

It would also help if methods has meaningful names, and so they become more "self documenting", and so people need to reach for the documentation less often. Like, what's `blt`? I know it's "blit". I think not even most of the pro developers does know that thing, and as it's shortened to be "blt", not even Google will tell them. O looked at the jumper example, ans same kind problem comes pop up there too. It has many of these: `pyxel.blt(0, 88, 0, 0, 64, 160, 24, 12)`. It's not self explanatory at all. As it's Python, it could be written like this instead: `pyxel.blt(0, 88, img=0, u=0, v=64, w=160, h=24, colkey=12)`. My on-topic point is, making things easier to understand perhaps should be become a higher priority everywhere. Especially as projects like these are often appealing for beginners and hobbyist, or for education.

**Comment by kitao** [comment]
The reason why I don't write the document in the code is to support for multiple languages.
And Pyxel's also deliberately adopts a nostalgic style such as limited number of colors and old-fashioned abbreviated names. Simply put, it's my preference.

However, I get a lot of questions about `blt` and `bltm`, so I'm going to add a brief explanatory diagram to the README.

**Comment by ddekany** [comment]
You should follow your personal preference of course. It's just that, with Python, you have already decided to gave up on the nostalgia when it comes to coding aspect (understandably... some assembly anyone?), so then... well, you get it.

As of color limitations, it's like a typical "16 bit" era graphics. On typical "8 bit" you also have the ~3 color per sprite/tile limitation, which is responsible for the typical NES look-and-feel.

**Comment by nejdetckenobi** [comment]
It's a bit sad to see this issue is closed without any pull requests.

**Comment by nejdetckenobi** [comment]
Could we have at least an explanation for the mechanics? Or the explanatory diagram you mentioned before?
