### ISSUE TITLE
[Feature Request] Use custom bitmap fonts.

### ISSUE THREAD

**Issue by eliheuer** [kitao/pyxel#27]
I'm looking at the example files and I'm having trouble understanding exactly how the built-in font works. Is it currently possible to use custom bitmap fonts?

**Comment by kitao** [comment]
Yes. There's some limitation but you can try it.

Pyxel has the image bank for system font as the 5th bank, and you can access it with `pyxel.image(4)`. So if the size and layout of the font is the same, you can change it with `pyxel.image(4).load(0, 0, 'your 256x256 font image filename')`

And regarding the size of font, it is defined as `FONT_WIDTH` and 'FONT_HEIGHT` in the constants.py. But these values are used when the shaders are compiled in the initialization phase, so you need to change constants.py before execution instead of changing it on the fly.

**Comment by kitao** [comment]
Oh, there are simpler way to use external font.
Just lord font image to some image bank with `pyxel.image(0).load(0, 0, 'bitmapfont.png').
After that, just draw it with `blt` command for every character. I think this is the commonly used method on 2D game engines.
