### ISSUE TITLE
Draw and Update

### ISSUE THREAD

**Issue by techpixel** [kitao/pyxel#274]
Why is draw and update separate functions? I think it would be easier that everything would run under one function instead of having so many variables communicating between functions.

**Comment by kitao** [comment]
Because if these functions are separated, the system can control the application's update timing more stable and reduce extra drawing load automatically. As a result of that, user's code also can be reduced.
It is the reason why other game engines such as PICO-8, Unity, Unreal Engine, etc. adopts this updating method.

If you would like to write update process and draw process in the same code block, Pyxel also provides ``flip`` method. (Please check README)
By using ``flip``, you can write codes as what you requested.

**Comment by techpixel** [comment]
Ahh, I see. Thanks for letting me know.

**Comment by danbst** [comment]
I still think, doc should be more specific on consequences of using drawing API in `update`, and consequences of making all game logic in `draw`. "Under-the-hood" details on what happens in those cases would be appreciated. Right now the distinction is purely aesthetic (from my POV).

**Comment by merwok** [comment]
> having so many variables communicating between functions

Many variables can be avoided by using instances, closures or coroutines.
