### ISSUE TITLE
[v2] Support configuring path for screenshots

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#318]
**Is your feature request related to a problem? Please describe.**
Using pyxel v2, tried to take a screenshot, got:
```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 2, kind: NotFound, message: "No such file or directory" })', engine/src/capturer.rs:95:54
```

Diagnostic: tries to save to `~/Desktop`, which I don’t have.

**Describe the solution you'd like**
Allow configuring screenshots directory in a config file

**Describe alternatives you've considered**
Follow XDG Base Dir specification to find configured pictures directory

**Additional context**
Btw, Alt+number are not very convenient shortcuts on azerty layouts for example.  Using Fnum keys is easier, or make them configurable.

**Comment by kitao** [comment]
In 1.5.0, Pyxel search for the existing directory with system environment and registry.

**Comment by duartqx** [comment]
Hello, I'm using `pyxel==1.6.9` and since I also don't have a Desktop folder, I had a crash related to this when tried to save a screenrecording. Can I change the recording path by changing a pyxel variable? I've looked in the list of variables and functions available in my editor and didn't saw anything related to it. Maybe it's an argument in the pyxel.screencast function? But since the function doesn't have a docstring I couldn't check

thread '<unnamed>' panicked at 'Unable to open file '/home/myuser/Desktop/pyxel-20220328-151843.gif'', engine/src/screencast.rs:119:33
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "/home/myuser/.local/bin/repos/pyxel_learning/flip.py", line 8, in <module>
    pyxel.flip()
pyo3_runtime.PanicException: Unable to open file '/home/myuser/Desktop/pyxel-20220328-151843.gif'

shell returned 1

**Comment by merwok** [comment]
This is still a problem.  I don’t have `~/Desktop`, I do have `XDG_DESKTOP_DIR` and `XDG_PICTURES_DIR` configured in the environment, but pyxel ignores them and crashes.
