### ISSUE TITLE
What does : "The specifications ... of Pyxel are referring to ..PICO-8 and TIC-80." mean?

### ISSUE THREAD

**Issue by bradparks** [kitao/pyxel#33]
Does this mean it's api compatible with PICO-8? Or TIC-80? 

If not, why not, and if so, please state it plainly!

I'm new to this bit, and am trying to build games using a cross platform api that's simple, well supported, and has lots of examples.

Between PICO-8 and it's port to LOVE, 
https://github.com/picolove/picolove

I wonder what this brings to the table, with the direct comparison in your readme?

Thanks so much - not meaning this to sound negative in anyway, I'd just like to know!

Much appreciated ;-)

Brad

**Comment by kitao** [comment]
No. Pyxel is incompatible with PICO-8 and TIC-80.
(As a precautionary note, PICO-8 and TIC-80 are different game engine and looks similar but different API. On the other hand, picolove is  a kind of PICO-8 clone using Love2D engine, so compatibility is very important.)

In my opinion, PICO-8, TIC-80, and Pyxel are the same for the purpose of enjoying retro game development, but its policy and target specs are different. Especially, Pyxel is using Python instead of Lua like other engines, API compatibility has little meaning.

One of the Pyxel's policy is simplicity. So I chose Python which is easy-to-learn language and referred the excellent simple API of other engines. On the other hand I didn't refer API for complex functions intentionally.

So I think the best way to use this kind of "fantasy console/retro game engine" is choosing something that fits your taste like choosing Mac and Windows. And I recommend Pyxel if you feel like going to game development and like Python.

I hope this information is helpful for you.

**Comment by bradparks** [comment]
Thanks a ton for the info - that definitely helps me understand what it is, and where it's going. I think Python is a wise choice to, for what it's worth. Thanks again!
