### ISSUE TITLE
Add setting to disable version check

### ISSUE THREAD

**Issue by merwok** [kitao/pyxel#374]
Can you add a way to opt out of new version checks?  People have many ways to keep track of new versions, so making a request to a server when running a local program is unnecessary (and even rude depending on the operating system culture 😉).  An environment variable like `PYXEL_DISABLE_CHECK_VERSION` could work.

**Comment by kitao** [comment]
Only Pyxel command help has a feature to check the version. In normal usages, it doesn’t happen at all.
About 90% of bug reports I got is caused by using older version and many PyPI users doesn’t notice there’s newer version according statistics. So I keep this feature and check how things goes.
Of source, it’s OK that skillful users modify Pyxel code to disable that command help’s feature.
