### ISSUE TITLE
Web version : download and infinite loop with editor when saved

### ISSUE THREAD

**Issue by laurentabbal** [kitao/pyxel#428]
Hi,

On https://kitao.github.io/pyxel/wasm/examples/image_editor.html, if I click on "save", it doesn't save the editor in the `Pyodide` filesystem but it downloads it indefinitely.
Same, with :
```
pyodide.runPython(`import pyxel.editor; pyxel.save("/pyxel_working_directory/res.pyxres")`);
```
Before, `res.pyxres` was saved in the Pyodide filesystem. Now, `res.pyxres` is downloaded.

I use Chrome and Windows.

**Comment by kitao** [comment]
It's an intentional specification.
In the current Pyxel Web, users can download files when saved because without that feature, users have no way to get files.
But it is done with normal saving operations. And by overriding _savePyxelFile function in JavaScript, downloading feature can be canceled manually.

**Comment by laurentabbal** [comment]
Hi. Thanks. 
It seems that it was was a cache problem on my side. My browser was downloading the same file over and over.
