### ISSUE TITLE
Feature request: save and load player game data (ex: high scores)

### ISSUE THREAD

**Issue by brettchalupa** [kitao/pyxel#474]
I'd like to make a feature request for two methods to easily save and load player data in a way that's cross-platform and works on web. Maybe the API could look like:

``` python
high_score = pyxel.load_data("high-score")
high_score = int(high_score)
pyxel.save_data("high-score", high_score)
```

Ideally the save data would be placed in a safe directory according to the operating system. The Godot engine uses these paths:

![godot save file locations](https://user-images.githubusercontent.com/928367/231027593-58ee5c62-4a8c-4052-bd15-e370acf1473b.png)

[docs](https://docs.godotengine.org/en/stable/tutorials/io/data_paths.html)

and maybe web could just use `localStorage`?

Just a simple key value store would be enough for most purposes.

Pico-8 has `dset(0, "my data")` and `dget(0)` for similar purposes.

Here are some use cases for why I'm requesting this:

- Save player high score for a shooting game
- Persist and load preferences for things like turning off music, sound effects, camera shake, etc.

Would this be a welcome contribution? I'd be happy to help and open a PR if so. Thanks!

**Comment by kitao** [comment]
Thank you for considering this. I've also explored similar possibilities in the past.

However, unlike PICO-8, Pyxel has features that are beginner-friendly and allow for arbitrary extensions in Python. Therefore, I think it's clearer and more understandable for each app to have its own Python code, innovatively designed to achieve such processes, rather than having apps inadvertently create data in unnoticed places without the user's intention.

Of course, I welcome the publication of utilities for Pyxel that can perform such processes. (In the past, someone added a feature to convert app suspension data into QR codes.)

**Comment by brettchalupa** [comment]
Makes total sense, thanks for considering it @kitao!
