### ISSUE TITLE
Linux Arm Support (Pi, botocera etc)

### ISSUE THREAD

**Issue by csevier** [kitao/pyxel#475]
Hello! Wonderful system. I am just curious, is there support for Linux Arm systems on the roadmap and if so, hows it going? Things like the raspberry pi, Amlogic, rockchips etc. I am looking to have Pyxel on retro handhelds, arcade machines etc. Things that motivate students. Happy to help in anyway I can! Thanks again.

**Comment by csevier** [comment]
I just found this blog post of yours https://tkitao.hatenablog.com/entry/2022/10/08/174438

It seems to indicate that arm is already supported. Can you confirm:

```
Pyxel was originally multi-platform, but 1.8 expands support to the following platforms:

    [Intel](http://d.hatena.ne.jp/keyword/Intel) 64-bit [Windows](http://d.hatena.ne.jp/keyword/Windows)
    [Intel](http://d.hatena.ne.jp/keyword/Intel) 32-bit [Windows](http://d.hatena.ne.jp/keyword/Windows)
    ARM 64-bit [Mac](http://d.hatena.ne.jp/keyword/Mac) (M1/M2 [Mac](http://d.hatena.ne.jp/keyword/Mac))
    [Intel](http://d.hatena.ne.jp/keyword/Intel) 64-bit [Mac](http://d.hatena.ne.jp/keyword/Mac)
    [Intel](http://d.hatena.ne.jp/keyword/Intel) 64-bit [Linux](http://d.hatena.ne.jp/keyword/Linux)
    [Intel](http://d.hatena.ne.jp/keyword/Intel) 32-bit [Linux](http://d.hatena.ne.jp/keyword/Linux)
    ARM 64-bit [Linux](http://d.hatena.ne.jp/keyword/Linux) (including Chromebooks)
```

**Comment by merwok** [comment]
ARM 64-bit seems to be the `aarch64` architecture recently introduced by Apple.
Raspberry Pi and other single-board computers need 32-bit ARM v6 with hard-float extensions or v7, codename `armhf`.

**Comment by csevier** [comment]
> ARM 64-bit seems to be the `aarch64` architecture recently introduced by Apple. Raspberry Pi and other single-board computers need 32-bit ARM v6 with hard-float extensions or v7, codename `armhf`.

Ahh great point! Additionally I should have made it more clear. I am interested in Linux running on Single Board Computers. Of course this is not standard, it comes down to the SBC and its cpu. However, I am most interested in the raspberry pi.

**Comment by kitao** [comment]
Hi. The official platforms supported by Pyxel can be most reliably found by looking at the Pyxel build scripts on GitHub.

https://github.com/kitao/pyxel/blob/main/.github/workflows/build.yml

As of today, the platforms supported by Pyxel are:
- Windows (32bit, 64bit)
- Mac on macOS 12 and later (64bit, 64bit ARM)
- Linux supported by [manylinux2014](https://peps.python.org/pep-0599/) (32bit, 64bit, 64bit ARM)

For Raspberry Pi, regardless of the version, it uses a 32bit OS and is not officially supported by Pyxel. However, if you have Raspberry Pi 3 or 4, there is a high possibility that it will work if you install a 64bit OS.

However, there have been people who have run Pyxel on Raspberry Pi in the past, and they did their own builds. The procedure for self-building is written in this file.

https://github.com/kitao/pyxel/blob/main/Makefile

The lack of support for 32bit ARM is due to errors that occurred in GitHub's build environment when we tried building it in the past. I don't believe it's impossible to support, so if there's a high demand from others who also want to run Pyxel on Raspberry Pi (without self-building), I would consider addressing this in the future.

**Comment by kitao** [comment]
@csevier Pyxel 1.9.17 should support Raspberry Pi. Please try it.

**Comment by csevier** [comment]
Thank you!
