### ISSUE TITLE
When I run an HTML application with ver 2.0, the assets file does not load properly.

### ISSUE THREAD

**Issue by shiromofufactory** [kitao/pyxel#504]
I get the error in the attached image. Looking at the console, I see a log that seems to refer to "/Users/takashi/Library/CloudStorage/OneDrive-個人用".

<img width="1387" alt="SS 2023-12-09 11 29 59" src="https://github.com/kitao/pyxel/assets/53714664/fc38486e-0608-4d61-a374-391ca2e218e1">

**Comment by kitao** [comment]
Please wait for about eight hours.

The old Pyxel is used due to CDN server’s caching feature. But sample code
and assets are used in the latest GitHub’s version. As the result of that,
old Pyxel failed to load new format resource.

But CDN’s cache should be updated later.

2023年12月9日(土) 11:34 shiromofufactory ***@***.***>:

**Comment by pke1029** [comment]
Is there any way to keep using the pre-2.0 Pyxel for older HTML builds? I have games made with Pyxel <=1.9.18, and they are now broken. All the sprites are not showing up correctly. I suspect it has something to do with issue #508, but using a different CDN link would be a quicker fix.

**Comment by merwok** [comment]
Pick the version you want on this page: https://cdn.jsdelivr.net/gh/kitao/pyxel/wasm/ (with the drop-down on the top right)
Then edit your HTML page to change the JS reference
