### ISSUE TITLE
Add functions `tri()` and `trib()` for drawing triangles.

### ISSUE THREAD

**Issue by marespiaut** [kitao/pyxel#52]
Hello,

As the title says, I would like to request the implementation of the functions `tri()` and `trib()` for drawing triangles on screen.

**Comment by kitao** [comment]
Hi, I would like to think carefully about polygon feature implementation. Because it needs too many arguments, especially in the case of using texture. On the other hand its application is limited unless there is proper 3D engine.

I'll consider this again in the feature, after the next big feature, the image and sound editor, is implemented.
