### ISSUE TITLE
pyxel edit gave wrong click in osx

### ISSUE THREAD

**Issue by Hulk89** [kitao/pyxel#587]
I uses pyxel edit by following condition.

* Apple M3 Max
* Sequoia 15.1.1
* sdl2 2.30.10
* python 3.11.1
* pyxel 2.2.8

When I click with the mouse, it takes about a second to respond, which is very slow.

And it's also intermittent double-clicking, so I can't utilize the utility properly.

Is there a solution or workaround?

P.s. It's a really good framework that I've been looking for. And I'm looking forward to making a simple game over the holidays.

**Comment by Hulk89** [comment]
By the way, It's same issue as https://github.com/kitao/pyxel/issues/282

**Comment by kitao** [comment]
If you mean that you are trying to use Pyxe Editor, could you check Pyxel examples? Because Pyxel Editor is just a Pyxel application written in Python. So the same issue should occur in examples. I'd like to confirm it first.

Anyway my main development environment is Mac and I can't reproduce the issue for now, we need to clarify what the difference is.

**Comment by Hulk89** [comment]
Yes. The same mouse lag persists in example 06 as in the issue above.

I tried cloning the github repository and building it, but the behavior was the same.

When I looked on stackoverflow, I saw that there is a similar lag when using the metal backend in the SDL, but I didn't know what options to give at build time to change from metal to opengl, so I didn't try it.

If you can point me to a way to use the opengl backend, I'll try it and let you know the results.

**Comment by Hulk89** [comment]
I updated sequoia 15.1.1 to 15.2 and problem solved.

I think it's osx's bug because this issue also occurred when I formatted and clean install 15.1.1
